model {
  file: "model.sdf"
  file_format {
    version {
      major: 1
      minor: 6
    }
    name: "sdf"
  }
}
name: "Urban Wall Debris"
description: "Wall debris for urban environment"
authors {
  name: "Cole Biesemeyer"
  email: "cole@openrobotics.org"
}

